FROM node:14.16.1 as builder
WORKDIR /usr/src/app 
COPY . ./
RUN rm -rf tap  && mkdir /webapp tap && chown node /webapp tap
ENV NODE_ENV production \
    NODE_PATH ./node_modules/:./lib/:./lib/web-app/ \
    NODE_CONFIG_ENV test 

RUN npm build

# # # RUN npm i  --only=production && \
# RUN npm run init-react-loadable 
# # RUN npm i --legacy-peer-dep
# # RUN npm run build
# RUN npm run build_prep &&  npm run build_install


FROM nginx:latest
WORKDIR /webapp
COPY --from=builder /usr/src/app/dist/server/ ./ 
COPY --from=builder /usr/src/app/dist/browser/ ./
RUN /bin/ls -lFa /usr/src/app/dist /webapp
EXPOSE 8080
USER node
CMD ["node", "."]
