// @TODO: this will continue to exist for documentation purposes

export const actionButtonSchema = {
  episode: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  episodeYoga: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  episodeMeditation: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  segment: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  segmentYoga: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  segmentFitness: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  segmentMeditation: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    fullSeries: true,
    moreDetails: true,
  },
  video: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    moreDetails: true,
  },
  videoYoga: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    moreDetails: true,
  },
  videoFitness: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    moreDetails: true,
  },
  videoMeditation: {
    watchNow: true,
    addToPlaylist: true,
    share: true,
    preview: true,
    moreDetails: true,
  },
}

export const metadataSchema = {
  episode: {
    seriesTitle: true,
    seriesId: true,
    duration: true,
    season: true,
    episode: true,
    year: true,
    guest: true,
  },
  episodeYoga: {
    instructor: true,
    seriesTitle: true,
    seriesId: true,
    season: true,
    episode: true,
    yogaDuration: true,
    yogaLevel: true,
    yogaStyle: true,
  },
  episodeMeditation: {
    instructor: true,
    seriesTitle: true,
    seriesId: true,
    season: true,
    episode: true,
    duration: true,
    meditationStyle: true,
  },
  segment: {
    seriesTitle: true,
    seriesId: true,
    duration: true,
    season: true,
    episode: true,
    year: true,
    guest: true,
  },
  segmentYoga: {
    instructor: true,
    seriesTitle: true,
    seriesId: true,
    season: true,
    episode: true,
    yogaDuration: true,
    yogaLevel: true,
    yogaStyle: true,
  },
  segmentFitness: {
    instructor: true,
    seriesTitle: true,
    seriesId: true,
    season: true,
    episode: true,
    fitnessDuration: true,
  },
  segmentMeditation: {
    instructor: true,
    seriesTitle: true,
    seriesId: true,
    season: true,
    episode: true,
    duration: true,
    meditationStyle: true,
  },
  series: {
    totalEpisodes: true,
    totalSeasons: true,
    host: true,
  },
  seriesYoga: {
    totalEpisodes: true,
    totalSeasons: true,
    host: true,
  },
  seriesFitness: {
    totalEpisodes: true,
    host: true,
  },
  seriesMeditation: {
    totalEpisodes: true,
    host: true,
  },
  video: {
    duration: true,
  },
  videoYoga: {
    instructor: true,
    yogaDuration: true,
    yogaLevel: true,
    yogaStyle: true,
  },
  videoFitness: {
    instructor: true,
    fitnessDuration: true,
    fitnessLevel: true,
    fitnessStyle: true,
  },
  videoMeditation: {
    instructor: true,
    duration: true,
    meditationStyle: true,
  },
}
